--- 
title: "BMP Dashboard Manual"
author: "Ané Cloete"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
link-citations: yes
github-repo: rstudio/bookdown-demo
---

```{r, include = FALSE}

knitr::opts_chunk$set(eval=FALSE)

```

# Hi :)

Everything you need to know to takeover the maintaining and building of the BMP dashboard is in this bookdown. The first chapter will outline the R project folder structure and contents and then in Chapter two I'll talk about how to get the biodiversity data form OneDrive and prepare the data for the dashboard. The remaining chapters will delve into the code itself. 

Before starting, here is a short list of handy resources: 

- [R](https://bookdown.org/yih_huynh/Guide-to-R-Book/)

- [Shiny # 1](https://shiny.posit.co/r/articles/#user-interface)

- [Shiny # 2](https://mastering-shiny.org/)

- [Github](https://happygitwithr.com/existing-github-last)

- [Bookdown](https://bookdown.org/yihui/bookdown/get-started.html) (if you want to know how to make something like this). 

- [HTML and CSS](https://unleash-shiny.rinterface.com/)

These are big and comprehensive resources that will aid you along the way. But remember google and [stackoverflow](https://stackoverflow.com/) are your best friends! And ChatGPT might become your closest and most frustrating colleague. 

## Owners 

- [Ané Cloete](https://www.linkedin.com/in/an%C3%A9-c-95629ab5/) (2023) 

If you are the new dashboard manager, add your name as well! All you need to do is open the bookdown project and navigate to the "index.Rmd" file and scroll down till you see this section. In the next chapter you'll see where this folder is located. 


Remember the dashboard is work in progress, so feel free to change and modify it as you like and most importantly have fun with it! Let's begin!

